export enum GraphemeBreakProperty {
    CR = 0,
    LF = 1,
    Control = 2,
    Extend = 3,
    Regional_Indicator = 4,
    SpacingMark = 5,
    L = 6,
    V = 7,
    T = 8,
    LV = 9,
    LVT = 10,
    Other = 11,
    Prepend = 12,
    E_Base = 13,
    E_Modifier = 14,
    ZWJ = 15,
    Glue_After_Zwj = 16,
    E_Base_GAZ = 17,
}
